# Generated by Django 2.1.7 on 2019-03-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='deadline',
        ),
    ]
