# Generated by Django 2.1.7 on 2019-03-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='div',
        ),
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignment'),
        ),
        migrations.AddField(
            model_name='practical',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='practical'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notes'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='practical',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='practical',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
