# Generated by Django 2.1.7 on 2019-03-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_assignment',
            name='file',
            field=models.FileField(upload_to='assignment'),
        ),
        migrations.AlterField(
            model_name='student_practical',
            name='file',
            field=models.FileField(upload_to='practical'),
        ),
    ]
