# Generated by Django 2.1.7 on 2019-03-24 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sub', models.CharField(max_length=256)),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=50)),
                ('batch', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4')], max_length=50, null=True)),
                ('div', models.BooleanField(default=False)),
                ('batch_check', models.BooleanField(default=False)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=256)),
                ('dept', models.CharField(choices=[('computer engineering', 'computer engineering'), ('it engineering', 'it engineering'), ('production engineering', 'production engineering'), ('mechanical engineering', 'mechanical engineering'), ('chemical engineering', 'chemical engineering'), ('bio-med engineering', 'bio-med engineering')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.PositiveIntegerField()),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20)),
                ('div', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=20)),
                ('batch', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4')], max_length=20)),
                ('dept', models.CharField(choices=[('computer engineering', 'computer engineering'), ('it engineering', 'it engineering'), ('production engineering', 'production engineering'), ('mechanical engineering', 'mechanical engineering'), ('chemical engineering', 'chemical engineering'), ('bio-med engineering', 'bio-med engineering')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(choices=[('computer engineering', 'computer engineering'), ('it engineering', 'it engineering'), ('production engineering', 'production engineering'), ('mechanical engineering', 'mechanical engineering'), ('chemical engineering', 'chemical engineering'), ('bio-med engineering', 'bio-med engineering')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(to='home.students'),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacher'),
        ),
    ]
