# Generated by Django 2.1.7 on 2019-03-22 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('sub', models.CharField(max_length=256)),
                ('div_or_batch', models.CharField(max_length=50)),
                ('div', models.BooleanField(default=False)),
                ('batch', models.BooleanField(default=False)),
                ('year', models.CharField(max_length=256)),
                ('dept', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.PositiveIntegerField()),
                ('year', models.CharField(max_length=20)),
                ('div', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(to='home.students'),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.teacher'),
        ),
    ]
