# Generated by Django 2.1.7 on 2019-03-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='dept',
            field=models.CharField(blank=True, choices=[('computer engineering', 'computer engineering'), ('it engineering', 'it engineering'), ('production engineering', 'production engineering'), ('mechanical engineering', 'mechanical engineering'), ('chemical engineering', 'chemical engineering'), ('bio-med engineering', 'bio-med engineering')], max_length=200),
        ),
    ]
